export const FIND_ADDRESS_STARTED = "FIND_ADDRESS_STARTED";
export const FIND_ADDRESS_SUCCESS = "FIND_ADDRESS_SUCCESS";
export const FIND_ADDRESS_FAILURE = "FIND_ADDRESS_FAILURE";

export const AVAILABILITY_CHECK_STARTED = "AVAILABILITY_CHECK_STARTED";
export const PHONE_NUMBER_AVAILABILITY_CHECK_SUCCESS =
  "PHONE_NUMBER_AVAILABILITY_CHECK_SUCCESS";
export const PHONE_NUMBER_AVAILABILITY_CHECK_FAILURE =
  "PHONE_NUMBER_AVAILABILITY_CHECK_FAILURE";
export const ADDRESS_AVAILABILITY_CHECK_SUCCESS =
  "ADDRESS_AVAILABILITY_CHECK_SUCCESS";
export const ADDRESS_AVAILABILITY_CHECK_FAILURE =
  "ADDRESS_AVAILABILITY_CHECK_FAILURE";
